name: Repo Visualizer (reusable)

on:
  workflow_call:

permissions:
  contents: write

jobs:
  diagram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Update repo diagram
        uses: githubocto/repo-visualizer@a999615bdab757559bf94bda1fe6eef232765f85 # v0.9.1
        with:
          output_file: images/diagram.svg
          excluded_paths: 'node_modules,dist,build,.next,vendor,Pods'
          should_push: true
          commit_message: 'chore: update repo diagram [skip ci]'